### DISCUSSION TITLE
Consider (additional) contribution to OpenRewrite to simplify version updates for users

### DISCUSSION THREAD

**Discussion by jjank** [hibernate/hibernate-orm#6759] [Design Proposals]
Hi Hibernate team,

I'm an active user of the [OpenRewrite-project](https://docs.openrewrite.org/). It is a _tremendous_ time and quality saver when upgrading/migrating applications.

There's already [detailed migration guides](https://github.com/hibernate/hibernate-orm/wiki/Migration-Guides) - that's great! 

Note that the OpenRewrite-team already has [some support for migrating to ORM 6.1](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/resources/META-INF/rewrite/hibernate-6.yml) but in my opinion there is room for more 😁 .

One concrete example from the [6.0 migration guide - Renaming of JavaTypeDescriptor contract](https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc#renaming-of-javatypedescriptor-contract) could be automated with the [Change type recipe](https://docs.openrewrite.org/recipes/java/changetype) in OpenRewrite:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.hibernate.orm.migrate
displayName: Renaming of JavaTypeDescriptor contract
recipeList:
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.hibernate.type.descriptor.java.JavaTypeDescriptor
      newFullyQualifiedTypeName: org.hibernate.type.descriptor.java.JavaType
      ignoreDefinition: null
```

I'm sure more examples can be found and might come up in the future.

So my point of discussion is: Would you consider either contributing to the exisiting OpenRewrite recipes and/or consider publishing your own recipes in the future? I'm cc-ing [Tim te Beek](https://github.com/timtebeek) from the OpenRewrite team who has offered help 😄 

Thank you very much for considering this!
Johannes
